### ISSUE TITLE
Documentation needs improvements

### ISSUE THREAD

**Issue by tbabej** [robgolding63/tasklib#12]
I just realized I did not include documentation for the new features from the pull request #11 . This issue is to track it, I don't have the time required on my hands right now.

**Comment by robgolding63** [comment]
Great work on those updates, and thank you again. Happy new year! I made you a collaborator on the repository so you don't have to wait for me in future, as you are clearly dedicated. I use 'git flow' for doing releases, which makes things fairly simple.
