### ISSUE TITLE
taskwarrior 3 support?

### ISSUE THREAD

**Issue by kbudde** [robgolding63/tasklib#134]
Hey,

is there any chance that this library will be updated to support the latest taskwarrior version?

Kind regards

Kris Budde

**Comment by smemsh** [comment]
does it not work for you? the library uses the execve/json interface, which hasn't changed, so it should still work ok.

**Comment by kbudde** [comment]
Hi,
I was testing with taskwiki and it created the old files.
It looks like a configuration error on my side. It's working now with taskwarrior 3.

Sorry.
