### ISSUE TITLE
Error saving unmodified tasks

### ISSUE THREAD

**Issue by niknow** [robgolding63/tasklib#17]
The function `save()` of a `Task` raises the exception `TaskWarriorException: Additional text must be provided` when a task is saved, but was not actually modified.

Minimum not working example:

	from tasklib.task import TaskWarrior
	tw = TaskWarrior(data_location='my_taskwarrior_path')
	task = tw.tasks.filter('id:1').get()
	print(task)  #prints the task with id=1 correctly
	task.save() #crashes

The reason for the exception is that in this case, the function `save` of the `Task` invokes the `execute_command` function of the `TaskWarrior` with an empty modification argument, i.e. the supplied `command_args`in this case are something like `task 1 modify` (which already throws this exception, if you type this into the console, because taskwarrior wants to modify something, but does not know what).

Is this behaviour intended? Users of the library, who simply want to save a task and do not care about whether or not it was actually modified could consider this a bug. On the other hand, throwing this exception gives the user of the library the opportunity to catch it and act on it (but only if this user knows that this `TaskWarriorException` is caused by the fact that the task is unmodified). Maybe one should change `save` such that it does not do anything at all to an unmodified task but returns some value, which allows to decide whether or nor it changed something.

**Comment by tbabej** [comment]
Fixed in develop, and covered by tests.
