### ISSUE TITLE
assumes ASCII for input and output

### ISSUE THREAD

**Issue by tfheen** [robgolding63/tasklib#2]
Platform: Debian testing, Python 2.7.6

It seems like the code assumes non-unicode for input:

In [5]: tw.tasks.pending()
Out[5]: ---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-5-0e7c0b0800b1> in <module>()
----> 1 tw.tasks.pending()

/usr/lib/python2.7/dist-packages/IPython/core/displayhook.pyc in **call**(self, result)
    245             self.start_displayhook()
    246             self.write_output_prompt()
--> 247             format_dict, md_dict = self.compute_format_data(result)
    248             self.write_format_data(format_dict, md_dict)
    249             self.update_user_ns(result)

/usr/lib/python2.7/dist-packages/IPython/core/displayhook.pyc in compute_format_data(self, result)
    155 
    156         """
--> 157         return self.shell.display_formatter.format(result)
    158 
    159     def write_format_data(self, format_dict, md_dict=None):

/usr/lib/python2.7/dist-packages/IPython/core/formatters.pyc in format(self, obj, include, exclude)
    150             md = None
    151             try:
--> 152                 data = formatter(obj)
    153             except:
    154                 # FIXME: log the exception

/usr/lib/python2.7/dist-packages/IPython/core/formatters.pyc in **call**(self, obj)
    479                 type_pprinters=self.type_printers,
    480                 deferred_pprinters=self.deferred_printers)
--> 481             printer.pretty(obj)
    482             printer.flush()
    483             return stream.getvalue()

/usr/lib/python2.7/dist-packages/IPython/lib/pretty.pyc in pretty(self, obj)
    360                             if callable(meth):
    361                                 return meth(obj, self, cycle)
--> 362             return _default_pprint(obj, self, cycle)
    363         finally:
    364             self.end_group()

/usr/lib/python2.7/dist-packages/IPython/lib/pretty.pyc in _default_pprint(obj, p, cycle)
    480     if getattr(klass, '__repr__', None) not in _baseclass_reprs:
    481         # A user-provided repr.
--> 482         p.text(repr(obj))
    483         return
    484     p.begin_group(1, '<')

/usr/lib/python2.7/dist-packages/tasklib/task.pyc in **repr**(self)
    186 
    187     def **repr**(self):
--> 188         data = list(self[:REPR_OUTPUT_SIZE + 1])
    189         if len(data) > REPR_OUTPUT_SIZE:
    190             data[-1] = "...(remaining elements truncated)..."

/usr/lib/python2.7/dist-packages/tasklib/task.pyc in **getitem**(self, k)
    203     def **getitem**(self, k):
    204         if self._result_cache is None:
--> 205             self._result_cache = list(self)
    206         return self._result_cache.__getitem__(k)
    207 

/usr/lib/python2.7/dist-packages/tasklib/task.pyc in **iter**(self)
    198     def **iter**(self):
    199         if self._result_cache is None:
--> 200             self._result_cache = self._execute()
    201         return iter(self._result_cache)
    202 

/usr/lib/python2.7/dist-packages/tasklib/task.pyc in _execute(self)
    230         Fetch the tasks which match the current filters.
    231         """
--> 232         return self.warrior.filter_tasks(self.filter_obj)
    233 
    234     def all(self):

/usr/lib/python2.7/dist-packages/tasklib/task.pyc in filter_tasks(self, filter_obj)
    310         args = ['export', '--'] + filter_obj.get_filter_params()
    311         tasks = []
--> 312         for line in self.execute_command(args):
    313             if line:
    314                 data = line.strip(',')

/usr/lib/python2.7/dist-packages/tasklib/task.pyc in execute_command(self, args, config_override)
    298         p = subprocess.Popen(command_args, stdout=subprocess.PIPE,
    299                              stderr=subprocess.PIPE)
--> 300         stdout, stderr = [x.decode() for x in p.communicate()]
    301         if p.returncode:
    302             if stderr.strip():

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 42: ordinal not in range(128)

LANG is nb_NO.UTF-8.

**Comment by er4z0r** [comment]
I still have UTF-8 problems when filtering tasks:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from tasklib.task import *

tw = TaskWarrior(data_location='~/.task', create=False)

local = tw.tasks.filter(description__contains=u'Täst')
print local 
```
Still gives me this:
```
Traceback (most recent call last):
  File "täst.py", line 7, in <module>
    local = tw.tasks.filter(description__contains=u'Täst')
  File "build/bdist.macosx-10.10-x86_64/egg/tasklib/task.py", line 843, in filter
  File "build/bdist.macosx-10.10-x86_64/egg/tasklib/task.py", line 743, in add_filter_param
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 2: ordinal not in range(128)
```
Did I do it wrong?

**Comment by tbabej** [comment]
This is a valid issue, please open a new one.

In the meantime, I pushed a test for this to the devel branch.

**Comment by tbabej** [comment]
The issue should be fixed in the devel branch. Let us know if you have any other problems!

**Comment by er4z0r** [comment]
@tbabej  fix confirmed. Thank you for your quick response!
