### ISSUE TITLE
A ical exporter for scheduled tasks would be nice

### ISSUE THREAD

**Issue by muelli** [robgolding63/tasklib#35]
taskwarrior ships with a VTODO export PERL script.
I'm thinking of something what can export an iCal file with VEVENTS for, say, scheduled tasks, only.
It should be simple with the vobject library and this taskwarrior python bindinds...

**Comment by robgolding63** [comment]
Thanks for the suggestion! I think that kind of thing is a little out of scope for this project, though as you say it should be fairly easy to build using `tasklib` as a base. Closing this issue, but let us know if you end up writing something which we can link to in the docs!
