### ISSUE TITLE
Tags should be represented by sets rather than by lists

### ISSUE THREAD

**Issue by tbabej** [robgolding63/tasklib#38]
As they are essentially sets anyway. List representation can cause TW to interpret the tag multiple times, if used by a hook.

**Comment by tbabej** [comment]
Fixed in develop.

**Comment by xerus2000** [comment]
Ah, so this is the cause of https://github.com/tbabej/taskpirate/issues/11

But for some reason my pip installs tasklib 1.3.0 and doesn't find or accept any newer version...

**Comment by xerus2000** [comment]
oh wait, I think I misunderstood your point - it was about the internal datastructure, not the serialization...
