### ISSUE TITLE
Remove restrictive six version requirement

### ISSUE THREAD

**Issue by languitar** [robgolding63/tasklib#43]
The very restrictive exact requirement on a specific version of six prevents to package this software easily in a distribution. Any reason for this?

**Comment by tbabej** [comment]
I think it was left this way by mistake. There's been a commit 432b3aa67c40dd92ba2cb0042439ea665b2dcc21 which removed this restriction, and a later commit c9db4bbc93086f404c6d115df17e272989d2c310 that day reintroduced it.

@robgolding63 can you confim?

**Comment by robgolding63** [comment]
Looks like you're right @tbabej - let's  switch it back!

Thanks for the report @languitar.
